import { ENCLAVE_NAMING_CHECKPOINTS } from "@threa/types"

export const DYNAMIC_NAMING_CHECKPOINTS = ENCLAVE_NAMING_CHECKPOINTS
export const DYNAMIC_NAMING_QUIET_MS = 5_000
export const DYNAMIC_NAMING_SETTLING_KEEPS = 2
export const DYNAMIC_NAMING_CLAIM_LEASE_SECONDS = 60
export const DYNAMIC_NAMING_DECISION_TIMEOUT_MS = 40_000
export const DYNAMIC_NAMING_CLEANUP_LIMIT = 500
export const DYNAMIC_NAMING_MODEL_ID = "openrouter:openai/gpt-5.6-luna"
export const DYNAMIC_NAMING_TEMPERATURE = 0.3
export const DYNAMIC_NAMING_MAX_MESSAGES = 10
export const DYNAMIC_NAMING_MAX_EXISTING_TITLES = 10
