import type { AI } from "@threa/agent-runtime"
import type { KnowledgeType } from "@threa/types"
import type { ConfigResolver } from "../../lib/ai/config-resolver"
import { COMPONENT_PATHS } from "../../lib/ai/config-resolver"
import { MessageFormatter } from "../../lib/ai/message-formatter"
import type { Message } from "../messaging"
import type { Memo } from "./repository"
import {
  memoSetSchema,
  getMemorizerSystemPrompt,
  MEMORIZER_CONVERSATION_PROMPT,
  MEMORIZER_REVISION_PROMPT,
  MEMORIZER_EXISTING_TAGS_TEMPLATE,
} from "./config"

/**
 * A single single-topic memo generated by the memorizer.
 * Following GAM paper: self-contained abstracts that can stand alone.
 */
export interface MemoContent {
  title: string
  abstract: string
  knowledgeType: KnowledgeType
  keyPoints: string[]
  tags: string[]
  sourceMessageIds: string[]
}

/**
 * Context for memorization.
 * Includes prior abstracts for vocabulary consistency.
 */
export interface MemorizerContext {
  memoryContext: string[]
  content: Message | Message[]
  /** Active memos already attached to this conversation (for the regenerate-on-revision path). */
  existingMemos?: Memo[]
  existingTags?: string[]
  /** Workspace ID for cost tracking - required for cost attribution */
  workspaceId: string
  /** Author's timezone for date anchoring (IANA identifier, e.g., "America/New_York") */
  authorTimezone?: string
}

export class Memorizer {
  constructor(
    private ai: AI,
    private configResolver: ConfigResolver,
    private messageFormatter: MessageFormatter
  ) {}

  /**
   * Extract the set of single-topic memos worth remembering from a conversation.
   * Returns one memo per distinct topic; an empty array means nothing was worth keeping.
   */
  async memorizeConversation(formattedMessages: string, context: MemorizerContext): Promise<MemoContent[]> {
    const prompt = MEMORIZER_CONVERSATION_PROMPT.replace("{{MEMORY_CONTEXT}}", this.formatMemoryContext(context))
      .replace("{{MESSAGES}}", formattedMessages)
      .replace("{{EXISTING_TAGS_SECTION}}", this.formatExistingTags(context))

    return this.generateMemoSet(prompt, context, formattedMessages, {
      functionId: "memorize-conversation",
    })
  }

  /**
   * Memorize a conversation that already has memos: emit only the topics that are
   * new or changed since them. Existing memos are passed as context so unchanged
   * topics are not re-emitted; they are left untouched (additive, no supersession).
   */
  async reviseMemo(formattedMessages: string, context: MemorizerContext): Promise<MemoContent[]> {
    const existingMemos = context.existingMemos ?? []

    const prompt = MEMORIZER_REVISION_PROMPT.replace("{{MEMORY_CONTEXT}}", this.formatMemoryContext(context))
      .replace("{{EXISTING_MEMOS}}", this.formatExistingMemos(existingMemos))
      .replace("{{MESSAGES}}", formattedMessages)
      .replace("{{EXISTING_TAGS_SECTION}}", this.formatExistingTags(context))

    return this.generateMemoSet(prompt, context, formattedMessages, {
      functionId: "revise-memo",
      metadata: { existingMemoCount: existingMemos.length },
    })
  }

  private async generateMemoSet(
    prompt: string,
    context: MemorizerContext,
    formattedMessages: string,
    telemetry: { functionId: string; metadata?: Record<string, unknown> }
  ): Promise<MemoContent[]> {
    const config = await this.configResolver.resolve(COMPONENT_PATHS.MEMO_MEMORIZER)
    const messages = context.content as Message[]
    const messageCount = formattedMessages.split("<message").length - 1

    const { value } = await this.ai.generateObject({
      model: config.modelId,
      schema: memoSetSchema,
      messages: [
        { role: "system", content: getMemorizerSystemPrompt(context.authorTimezone) },
        { role: "user", content: prompt },
      ],
      temperature: config.temperature,
      telemetry: {
        functionId: telemetry.functionId,
        metadata: { messageCount, ...telemetry.metadata },
      },
      context: { workspaceId: context.workspaceId, origin: "system" },
    })

    return value.memos.map((memo) => {
      const validSourceIds = memo.sourceMessageIds.filter((id) => messages.some((m) => m.id === id))
      return {
        title: memo.title,
        abstract: memo.abstract,
        knowledgeType: memo.knowledgeType,
        keyPoints: memo.keyPoints,
        tags: memo.tags,
        sourceMessageIds: validSourceIds.length > 0 ? validSourceIds : messages.map((m) => m.id),
      }
    })
  }

  private formatMemoryContext(context: MemorizerContext): string {
    return context.memoryContext.length > 0
      ? context.memoryContext.map((a, i) => `${i + 1}. ${a}`).join("\n")
      : "No prior memos in this stream yet."
  }

  private formatExistingMemos(existingMemos: Memo[]): string {
    if (existingMemos.length === 0) {
      return "None."
    }
    return existingMemos.map((m, i) => `${i + 1}. ${m.title}\n   ${m.abstract}`).join("\n")
  }

  private formatExistingTags(context: MemorizerContext): string {
    return context.existingTags?.length
      ? MEMORIZER_EXISTING_TAGS_TEMPLATE.replace("{{TAGS}}", context.existingTags.join(", "))
      : ""
  }
}
