// Generic outbox infrastructure — re-exported from @threa/backend-common
export { OutboxDispatcher, type OutboxHandler, type OutboxDispatcherConfig } from "@threa/backend-common"
export { OutboxRetentionWorker, type OutboxRetentionWorkerConfig } from "@threa/backend-common"

// Domain-specific outbox code
export { BroadcastHandler, type BroadcastHandlerConfig } from "./broadcast-handler"
export {
  resolveDeliveryGroups,
  emitToGroups,
  groupToRoom,
  WORKSPACE_GROUP,
  streamGroup,
  userGroup,
} from "./delivery-groups"
export { parseMessagePayload, type NormalizedMessagePayload } from "./payload-parsers"
export {
  OutboxRepository,
  OUTBOX_CHANNEL,
  isOutboxEventType,
  isOneOfOutboxEventType,
  isStreamScopedEvent,
  isAuthorScopedEvent,
  type OutboxEventType,
  type StreamScopedEventType,
  type WorkspaceScopedEventType,
  type AuthorScopedEventType,
  type OutboxEvent,
  type OutboxEventPayload,
  type OutboxEventPayloadMap,
  type MessageCreatedOutboxPayload,
  type MessageEditedOutboxPayload,
  type MessageDeletedOutboxPayload,
  type MessageUpdatedOutboxPayload,
  type ReactionOutboxPayload,
  type StreamDisplayNameUpdatedPayload,
  type StreamCreatedOutboxPayload,
  type StreamUpdatedOutboxPayload,
  type StreamArchivedOutboxPayload,
  type StreamUnarchivedOutboxPayload,
  type AttachmentUploadedOutboxPayload,
  type AttachmentExtractionCompletedOutboxPayload,
  type WorkspaceUserAddedOutboxPayload,
  type WorkspaceUserRemovedOutboxPayload,
  type WorkspaceUserUpdatedOutboxPayload,
  type StreamMemberAddedOutboxPayload,
  type StreamMemberRemovedOutboxPayload,
  type StreamActivityOutboxPayload,
  type ConversationCreatedOutboxPayload,
  type ConversationUpdatedOutboxPayload,
  type MemoCreatedOutboxPayload,
  type CommandDispatchedOutboxPayload,
  type CommandCompletedOutboxPayload,
  type CommandFailedOutboxPayload,
  type AgentSessionStartedOutboxPayload,
  type AgentSessionCompletedOutboxPayload,
  type AgentSessionFailedOutboxPayload,
  type StreamReadOutboxPayload,
  type StreamsReadAllOutboxPayload,
  type UserPreferencesUpdatedOutboxPayload,
  type BotCreatedOutboxPayload,
  type BotUpdatedOutboxPayload,
  type BudgetAlertOutboxPayload,
  type InvitationAcceptedOutboxPayload,
  type ActivityCreatedOutboxPayload,
  type SavedUpsertedOutboxPayload,
  type SavedDeletedOutboxPayload,
  type SavedReminderFiredOutboxPayload,
  type LinkPreviewReadyOutboxPayload,
  type UserScopedEventType,
  isUserScopedEvent,
} from "./repository"
