import type { Request, Response } from "express"
import { z } from "zod"
import type { Pool } from "pg"
import { buildContentDisposition, buildUploadParams, parseE2eUploadFlag, type AttachmentService } from "./service"
import { isAttachmentReadableViaShareOrReference } from "./access"
import { AttachmentRepository, type AttachmentSearchCursor, type AttachmentSearchRow } from "./repository"
import { AttachmentExtractionRepository } from "./extraction-repository"
import type { StreamService } from "../streams"
import { VideoTranscodeJobRepository } from "./video"
import { isImageAttachment } from "./image-caption"
import type { StorageProvider } from "../../lib/storage/s3-client"
import { ATTACHMENT_CATEGORIES, type AttachmentCategory } from "@threa/types"

interface Dependencies {
  attachmentService: AttachmentService
  streamService: StreamService
  storage: StorageProvider
  pool: Pool
}

export function createAttachmentHandlers({ attachmentService, streamService, storage, pool }: Dependencies) {
  return {
    /**
     * Upload a file to the workspace.
     * Files are uploaded to workspace-level (no stream) and attached to a stream when linked to a message.
     * Workspace membership is checked by middleware.
     */
    async upload(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!

      // File was uploaded to S3 by multer-s3 middleware
      const file = req.file
      if (!file || !file.key) {
        return res.status(400).json({ error: "No file provided" })
      }

      // The attachment ID was generated by the upload middleware
      const attachmentId = req.attachmentId!

      // E2E upload: the body bytes are client-side ciphertext. buildUploadParams
      // forces placeholder metadata — the real filename/mime ride encrypted in
      // the message's attachmentRefs, never on this row.
      const uploadResult = await attachmentService.createForUpload(
        buildUploadParams(
          {
            id: attachmentId,
            workspaceId,
            uploadedBy: userId,
            filename: file.originalname,
            mimeType: file.mimetype,
            sizeBytes: file.size,
            storagePath: file.key,
          },
          parseE2eUploadFlag(req.body)
        )
      )

      if (uploadResult.status === "cleanup_failed") {
        return res.status(500).json({
          error: "Attachment quarantined and cleanup failed",
          attachmentId: uploadResult.attachmentId,
        })
      }

      if (uploadResult.status === "blocked") {
        return res.status(400).json({ error: uploadResult.reason })
      }

      res.status(201).json({ attachment: uploadResult.attachment })
    },

    /**
     * Get a presigned download URL for an attachment.
     * For attached files, checks stream membership.
     * For pending files (not yet attached), workspace usership is sufficient.
     */
    async getDownloadUrl(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      const sharingBlockReason = attachmentService.getSharingBlockReason(attachment)
      if (sharingBlockReason) {
        return res.status(403).json({ error: sharingBlockReason })
      }

      // Direct stream access first; if that fails, fall back to the
      // share-grant + inline-reference chain. Splitting the fast path from
      // the fallback lets the handler keep streamService injection (existing
      // mock surface) while the reusable rule lives in `access.ts`.
      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          const granted = await isAttachmentReadableViaShareOrReference(pool, attachment, workspaceId, userId)
          if (!granted) {
            return res.status(403).json({ error: "Access denied" })
          }
        }
      }

      const parsed = z
        .object({
          download: z.enum(["true", "false"]).optional(),
          variant: z.enum(["raw", "processed", "thumbnail"]).optional(),
        })
        .safeParse(req.query)
      if (!parsed.success) return res.status(400).json({ error: "Invalid query parameters" })
      const { download, variant } = parsed.data

      // Image thumbnail: serve the sharp-generated WebP variant when ready.
      // Generated asynchronously by the IMAGE_THUMBNAIL worker; if not yet
      // available, fall through to the raw original.
      if (variant === "thumbnail" && isImageAttachment(attachment.mimeType, attachment.filename)) {
        if (attachment.thumbnailStoragePath) {
          const responseContentDisposition =
            download === "true" ? buildContentDisposition(attachment.filename) : undefined
          const url = await storage.getSignedDownloadUrl(attachment.thumbnailStoragePath, {
            responseContentDisposition,
          })
          return res.json({ url, expiresIn: 900 })
        }
        // Thumbnail not generated yet — fall through to raw original.
      } else if (variant === "processed" || variant === "thumbnail") {
        // For video variants (processed/thumbnail), look up the transcode job
        const job = await VideoTranscodeJobRepository.findByAttachmentId(pool, attachmentId)
        const path = variant === "processed" ? job?.processedStoragePath : job?.thumbnailStoragePath
        if (job?.status === "completed" && path) {
          const filename =
            variant === "processed" ? attachment.filename.replace(/\.[^.]+$/, ".mp4") : attachment.filename
          const responseContentDisposition = download === "true" ? buildContentDisposition(filename) : undefined
          const url = await storage.getSignedDownloadUrl(path, { responseContentDisposition })
          return res.json({ url, expiresIn: 900 })
        }
        // Fall through to raw file if variant not available
      }

      const url = await attachmentService.getDownloadUrl(attachment, { download: download === "true" })
      res.json({ url, expiresIn: 900 })
    },

    /**
     * Delete an unattached file.
     * Only the user who uploaded the file can delete it.
     * Attached files cannot be deleted.
     */
    async delete(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      // Only allow deletion of unattached files
      if (attachment.messageId) {
        return res.status(403).json({ error: "Cannot delete attached files" })
      }

      // Only the uploader can delete their own pending files
      if (attachment.uploadedBy && attachment.uploadedBy !== userId) {
        return res.status(403).json({ error: "Cannot delete files uploaded by other users" })
      }

      await attachmentService.delete(attachmentId)
      res.status(204).send()
    },

    /**
     * Return the full extracted text for an attachment so the explorer
     * preview pane can show the complete content (and copy it). Reuses the
     * same access fast-path as `getDownloadUrl` — direct stream access first,
     * then share-grant + inline-reference fallback.
     */
    async getExtraction(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          const granted = await isAttachmentReadableViaShareOrReference(pool, attachment, workspaceId, userId)
          if (!granted) {
            return res.status(403).json({ error: "Access denied" })
          }
        }
      }

      const extraction = await AttachmentExtractionRepository.findByAttachmentId(pool, attachmentId)
      if (!extraction) {
        return res.status(404).json({ error: "Extraction not found" })
      }

      res.json({
        contentType: extraction.contentType,
        summary: extraction.summary,
        fullText: extraction.fullText,
      })
    },

    /**
     * Search attachments for the explorer modal.
     *
     * One round trip combining readable-stream gating (callers can never see
     * files in streams they can't read), thread-descendant expansion when
     * `streamIds` is supplied, FTS / exact substring search across filename
     * and extracted text, and keyset cursor pagination.
     *
     * Returns rows in `created_at DESC, id DESC` order with `nextCursor`
     * set when more pages are available.
     */
    async search(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!

      const parsed = SEARCH_BODY_SCHEMA.safeParse(req.body)
      if (!parsed.success) {
        return res.status(400).json({ error: "Invalid request body", details: parsed.error.format() })
      }
      const body = parsed.data

      const cursor = decodeCursor(body.cursor)
      if (body.cursor && !cursor) {
        return res.status(400).json({ error: "Invalid cursor" })
      }

      const limit = body.limit ?? DEFAULT_SEARCH_LIMIT

      const rows = await AttachmentRepository.search(pool, {
        workspaceId,
        userId,
        streamIds: body.streamIds,
        categories: body.categories,
        uploadedBy: body.uploadedBy,
        before: body.before ? new Date(body.before) : undefined,
        after: body.after ? new Date(body.after) : undefined,
        queryText: body.queryText,
        exact: body.exact ?? false,
        nameSubstring: body.nameSubstring,
        cursor,
        limit,
      })

      const hasMore = rows.length > limit
      const items = hasMore ? rows.slice(0, limit) : rows
      const last = items[items.length - 1]
      const nextCursor = hasMore && last ? encodeCursor({ createdAt: last.createdAt, id: last.id }) : null

      res.json({
        items: items.map(serializeSearchRow),
        nextCursor,
      })
    },
  }
}

const DEFAULT_SEARCH_LIMIT = 30
const MAX_SEARCH_LIMIT = 100

const SEARCH_BODY_SCHEMA = z
  .object({
    streamIds: z.array(z.string()).max(100).optional(),
    categories: z
      .array(z.enum(ATTACHMENT_CATEGORIES as readonly [AttachmentCategory, ...AttachmentCategory[]]))
      .max(20)
      .optional(),
    uploadedBy: z.string().optional(),
    before: z.string().datetime().optional(),
    after: z.string().datetime().optional(),
    queryText: z.string().max(500).optional(),
    exact: z.boolean().optional(),
    nameSubstring: z.string().max(200).optional(),
    cursor: z.string().optional(),
    limit: z.number().int().positive().max(MAX_SEARCH_LIMIT).optional(),
  })
  .strict()

function encodeCursor(cursor: AttachmentSearchCursor): string {
  return Buffer.from(JSON.stringify({ c: cursor.createdAt.toISOString(), i: cursor.id }), "utf8").toString("base64url")
}

function decodeCursor(raw: string | undefined): AttachmentSearchCursor | undefined {
  if (!raw) return undefined
  try {
    const parsed = JSON.parse(Buffer.from(raw, "base64url").toString("utf8"))
    if (typeof parsed?.c !== "string" || typeof parsed?.i !== "string") return undefined
    const createdAt = new Date(parsed.c)
    if (Number.isNaN(createdAt.getTime())) return undefined
    return { createdAt, id: parsed.i }
  } catch {
    return undefined
  }
}

function serializeSearchRow(row: AttachmentSearchRow) {
  return {
    id: row.id,
    workspaceId: row.workspaceId,
    streamId: row.streamId,
    messageId: row.messageId,
    uploadedBy: row.uploadedBy,
    filename: row.filename,
    mimeType: row.mimeType,
    sizeBytes: row.sizeBytes,
    storageProvider: row.storageProvider,
    storagePath: row.storagePath,
    processingStatus: row.processingStatus,
    safetyStatus: row.safetyStatus,
    createdAt: row.createdAt.toISOString(),
    extraction: row.extraction
      ? {
          contentType: row.extraction.contentType,
          summary: row.extraction.summary,
        }
      : null,
    streamSlug: row.streamSlug,
    streamName: row.streamName,
    streamType: row.streamType,
    uploaderSlug: row.uploaderSlug,
    uploaderName: row.uploaderName,
    referenceCount: row.referenceCount,
  }
}
