import { createHash } from "node:crypto"
import type { Request, Response } from "express"
import { z } from "zod"
import type { Pool } from "pg"
import { buildContentDisposition, buildUploadParams, parseE2eUploadFlag, type AttachmentService } from "./service"
import { isAttachmentReadableViaShareOrReference } from "./access"
import {
  AttachmentRepository,
  type Attachment,
  type AttachmentSearchCursor,
  type AttachmentSearchRow,
} from "./repository"
import { AttachmentExtractionRepository } from "./extraction-repository"
import type { StreamService } from "../streams"
import { VideoTranscodeJobRepository } from "./video"
import { isImageAttachment } from "./image-caption"
import type { StorageProvider } from "../../lib/storage/s3-client"
import { ATTACHMENT_CATEGORIES, type AttachmentCategory } from "@threa/types"

interface Dependencies {
  attachmentService: AttachmentService
  streamService: StreamService
  storage: StorageProvider
  pool: Pool
}

export function createAttachmentHandlers({ attachmentService, streamService, storage, pool }: Dependencies) {
  return {
    /**
     * Upload a file to the workspace.
     * Files are uploaded to workspace-level (no stream) and attached to a stream when linked to a message.
     * Workspace membership is checked by middleware.
     */
    async upload(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!

      // File was uploaded to S3 by multer-s3 middleware
      const file = req.file
      if (!file || !file.key) {
        return res.status(400).json({ error: "No file provided" })
      }

      // The attachment ID was generated by the upload middleware
      const attachmentId = req.attachmentId!

      // E2E upload: the body bytes are client-side ciphertext. buildUploadParams
      // forces placeholder metadata — the real filename/mime ride encrypted in
      // the message's attachmentRefs, never on this row.
      const uploadResult = await attachmentService.createForUpload(
        buildUploadParams(
          {
            id: attachmentId,
            workspaceId,
            uploadedBy: userId,
            filename: file.originalname,
            mimeType: file.mimetype,
            sizeBytes: file.size,
            storagePath: file.key,
          },
          parseE2eUploadFlag(req.body)
        )
      )

      if (uploadResult.status === "cleanup_failed") {
        return res.status(500).json({
          error: "Attachment quarantined and cleanup failed",
          attachmentId: uploadResult.attachmentId,
        })
      }

      if (uploadResult.status === "blocked") {
        return res.status(400).json({ error: uploadResult.reason })
      }

      res.status(201).json({ attachment: uploadResult.attachment })
    },

    /**
     * Get a presigned download URL for an attachment.
     * For attached files, checks stream membership.
     * For pending files (not yet attached), workspace usership is sufficient.
     */
    async getDownloadUrl(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      const sharingBlockReason = attachmentService.getSharingBlockReason(attachment)
      if (sharingBlockReason) {
        return res.status(403).json({ error: sharingBlockReason })
      }

      // Direct stream access first; if that fails, fall back to the
      // share-grant + inline-reference chain. Splitting the fast path from
      // the fallback lets the handler keep streamService injection (existing
      // mock surface) while the reusable rule lives in `access.ts`.
      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          const granted = await isAttachmentReadableViaShareOrReference(pool, attachment, workspaceId, userId)
          if (!granted) {
            return res.status(403).json({ error: "Access denied" })
          }
        }
      }

      const parsed = z
        .object({
          download: z.enum(["true", "false"]).optional(),
          variant: z.enum(["raw", "processed", "thumbnail"]).optional(),
        })
        .safeParse(req.query)
      if (!parsed.success) return res.status(400).json({ error: "Invalid query parameters" })
      const { download, variant } = parsed.data

      // A generated variant resolved to its own object → presign it. Raw
      // requests and not-ready fall-throughs presign the original below.
      const resolved = await resolveAttachmentVariant(pool, attachment, variant)
      if (resolved.ready && resolved.storagePath !== attachment.storagePath) {
        const responseContentDisposition = download === "true" ? buildContentDisposition(resolved.filename) : undefined
        const url = await storage.getSignedDownloadUrl(resolved.storagePath, { responseContentDisposition })
        return res.json({ url, expiresIn: 900 })
      }

      const url = await attachmentService.getDownloadUrl(attachment, { download: download === "true" })
      res.json({ url, expiresIn: 900 })
    },

    /**
     * Serve attachment bytes through the backend at a deterministic URL per
     * (attachment, variant), so the browser HTTP cache works across sessions —
     * unlike presigned URLs from `getDownloadUrl`, whose fresh signature
     * defeats cache keying and forces a re-download every cold open.
     *
     * Same ACL chain as `getDownloadUrl`: workspace scoping, sharing-safety
     * gate, direct stream access with the share-grant/inline-reference
     * fallback.
     *
     * The stored object for a given (attachment, variant) never changes after
     * processing completes, so ready variants are served `immutable`. The
     * not-ready fall-through (thumbnail/processed not generated yet) serves
     * the raw original with `no-store` — caching fallback bytes under the
     * variant URL would pin them and the real variant would never appear.
     */
    async getContent(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      const sharingBlockReason = attachmentService.getSharingBlockReason(attachment)
      if (sharingBlockReason) {
        return res.status(403).json({ error: sharingBlockReason })
      }

      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          const granted = await isAttachmentReadableViaShareOrReference(pool, attachment, workspaceId, userId)
          if (!granted) {
            return res.status(403).json({ error: "Access denied" })
          }
        }
      }

      const parsed = z
        .object({
          variant: z.enum(["raw", "processed", "thumbnail"]).optional(),
        })
        .safeParse(req.query)
      if (!parsed.success) return res.status(400).json({ error: "Invalid query parameters" })
      const { variant } = parsed.data

      const resolved = await resolveAttachmentVariant(pool, attachment, variant)

      // The storage path uniquely identifies the served bytes (objects are
      // written once), so a path-derived ETag is a valid validator. The
      // fall-through gets no validator — a 304 must never extend the life of
      // fallback bytes under the variant URL.
      const etag = `"${createHash("sha256").update(resolved.storagePath).digest("hex")}"`
      const cacheControl = resolved.ready ? "private, max-age=31536000, immutable" : "private, no-store"

      res.set("Cache-Control", cacheControl)
      res.set("X-Content-Type-Options", "nosniff")
      // User-authored bytes served from the app origin must never execute as a
      // document (HTML/SVG navigated to directly).
      res.set("Content-Security-Policy", "sandbox")
      if (resolved.ready) res.set("ETag", etag)

      if (resolved.ready && req.headers["if-none-match"] === etag) {
        return res.status(304).end()
      }

      const range = typeof req.headers.range === "string" ? req.headers.range : undefined
      const object = await storage.getObjectContent(resolved.storagePath, { range })

      res.set("Content-Type", resolved.contentType)
      res.set("Accept-Ranges", "bytes")
      if (object.contentLength !== undefined) res.set("Content-Length", String(object.contentLength))
      if (object.contentRange) {
        res.status(206)
        res.set("Content-Range", object.contentRange)
      }

      object.stream.on("error", (err) => {
        if (!res.headersSent) {
          res.status(500).end()
        } else {
          // Headers (including Content-Length) are already on the wire — abort
          // the socket so the client sees a failed transfer instead of a
          // cleanly-terminated truncated 200 it would treat as complete.
          res.destroy(err)
        }
      })
      object.stream.pipe(res)
    },

    /**
     * Delete an unattached file.
     * Only the user who uploaded the file can delete it.
     * Attached files cannot be deleted.
     */
    async delete(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      // Only allow deletion of unattached files
      if (attachment.messageId) {
        return res.status(403).json({ error: "Cannot delete attached files" })
      }

      // Only the uploader can delete their own pending files
      if (attachment.uploadedBy && attachment.uploadedBy !== userId) {
        return res.status(403).json({ error: "Cannot delete files uploaded by other users" })
      }

      await attachmentService.delete(attachmentId)
      res.status(204).send()
    },

    /**
     * Return the full extracted text for an attachment so the explorer
     * preview pane can show the complete content (and copy it). Reuses the
     * same access fast-path as `getDownloadUrl` — direct stream access first,
     * then share-grant + inline-reference fallback.
     */
    async getExtraction(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          const granted = await isAttachmentReadableViaShareOrReference(pool, attachment, workspaceId, userId)
          if (!granted) {
            return res.status(403).json({ error: "Access denied" })
          }
        }
      }

      const extraction = await AttachmentExtractionRepository.findByAttachmentId(pool, attachmentId)
      if (!extraction) {
        return res.status(404).json({ error: "Extraction not found" })
      }

      res.json({
        contentType: extraction.contentType,
        summary: extraction.summary,
        fullText: extraction.fullText,
      })
    },

    /**
     * Search attachments for the explorer modal.
     *
     * One round trip combining readable-stream gating (callers can never see
     * files in streams they can't read), thread-descendant expansion when
     * `streamIds` is supplied, FTS / exact substring search across filename
     * and extracted text, and keyset cursor pagination.
     *
     * Returns rows in `created_at DESC, id DESC` order with `nextCursor`
     * set when more pages are available.
     */
    async search(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!

      const parsed = SEARCH_BODY_SCHEMA.safeParse(req.body)
      if (!parsed.success) {
        return res.status(400).json({ error: "Invalid request body", details: parsed.error.format() })
      }
      const body = parsed.data

      const cursor = decodeCursor(body.cursor)
      if (body.cursor && !cursor) {
        return res.status(400).json({ error: "Invalid cursor" })
      }

      const limit = body.limit ?? DEFAULT_SEARCH_LIMIT

      const rows = await AttachmentRepository.search(pool, {
        workspaceId,
        userId,
        streamIds: body.streamIds,
        categories: body.categories,
        uploadedBy: body.uploadedBy,
        before: body.before ? new Date(body.before) : undefined,
        after: body.after ? new Date(body.after) : undefined,
        queryText: body.queryText,
        exact: body.exact ?? false,
        nameSubstring: body.nameSubstring,
        cursor,
        limit,
      })

      const hasMore = rows.length > limit
      const items = hasMore ? rows.slice(0, limit) : rows
      const last = items[items.length - 1]
      const nextCursor = hasMore && last ? encodeCursor({ createdAt: last.createdAt, id: last.id }) : null

      res.json({
        items: items.map(serializeSearchRow),
        nextCursor,
      })
    },
  }
}

interface ResolvedAttachmentVariant {
  storagePath: string
  contentType: string
  /**
   * Filename for content-disposition downloads, with its extension matching
   * the served bytes (.webp/.jpg thumbnails, .mp4 processed video) rather
   * than the original upload's.
   */
  filename: string
  /**
   * False when a generated variant was requested but isn't available yet —
   * callers serve the raw original instead and must NOT let it be cached
   * under the variant URL.
   */
  ready: boolean
}

/**
 * Resolve which stored object a (attachment, variant) pair maps to — the one
 * rule shared by `getDownloadUrl` (presign) and `getContent` (streaming).
 *
 * Image thumbnails are sharp-generated WebP, produced asynchronously by the
 * IMAGE_THUMBNAIL worker; video processed/thumbnail variants come from the
 * MediaConvert transcode job. Either may not exist yet, in which case the
 * raw original is the fall-through with `ready: false`.
 */
async function resolveAttachmentVariant(
  pool: Pool,
  attachment: Attachment,
  variant: "raw" | "processed" | "thumbnail" | undefined
): Promise<ResolvedAttachmentVariant> {
  if (variant === "thumbnail" && isImageAttachment(attachment.mimeType, attachment.filename)) {
    if (attachment.thumbnailStoragePath) {
      return {
        storagePath: attachment.thumbnailStoragePath,
        contentType: "image/webp",
        filename: attachment.filename.replace(/\.[^.]+$/, ".webp"),
        ready: true,
      }
    }
  } else if (variant === "processed" || variant === "thumbnail") {
    const job = await VideoTranscodeJobRepository.findByAttachmentId(pool, attachment.id)
    const path = variant === "processed" ? job?.processedStoragePath : job?.thumbnailStoragePath
    if (job?.status === "completed" && path) {
      return {
        storagePath: path,
        contentType: variant === "processed" ? "video/mp4" : "image/jpeg",
        filename: attachment.filename.replace(/\.[^.]+$/, variant === "processed" ? ".mp4" : ".jpg"),
        ready: true,
      }
    }
  } else {
    // Raw (or no variant) requested — the original is always available.
    return {
      storagePath: attachment.storagePath,
      contentType: attachment.mimeType,
      filename: attachment.filename,
      ready: true,
    }
  }

  // Requested variant not generated yet — raw fall-through.
  return {
    storagePath: attachment.storagePath,
    contentType: attachment.mimeType,
    filename: attachment.filename,
    ready: false,
  }
}

const DEFAULT_SEARCH_LIMIT = 30
const MAX_SEARCH_LIMIT = 100

const SEARCH_BODY_SCHEMA = z
  .object({
    streamIds: z.array(z.string()).max(100).optional(),
    categories: z
      .array(z.enum(ATTACHMENT_CATEGORIES as readonly [AttachmentCategory, ...AttachmentCategory[]]))
      .max(20)
      .optional(),
    uploadedBy: z.string().optional(),
    before: z.string().datetime().optional(),
    after: z.string().datetime().optional(),
    queryText: z.string().max(500).optional(),
    exact: z.boolean().optional(),
    nameSubstring: z.string().max(200).optional(),
    cursor: z.string().optional(),
    limit: z.number().int().positive().max(MAX_SEARCH_LIMIT).optional(),
  })
  .strict()

function encodeCursor(cursor: AttachmentSearchCursor): string {
  return Buffer.from(JSON.stringify({ c: cursor.createdAt.toISOString(), i: cursor.id }), "utf8").toString("base64url")
}

function decodeCursor(raw: string | undefined): AttachmentSearchCursor | undefined {
  if (!raw) return undefined
  try {
    const parsed = JSON.parse(Buffer.from(raw, "base64url").toString("utf8"))
    if (typeof parsed?.c !== "string" || typeof parsed?.i !== "string") return undefined
    const createdAt = new Date(parsed.c)
    if (Number.isNaN(createdAt.getTime())) return undefined
    return { createdAt, id: parsed.i }
  } catch {
    return undefined
  }
}

function serializeSearchRow(row: AttachmentSearchRow) {
  return {
    id: row.id,
    workspaceId: row.workspaceId,
    streamId: row.streamId,
    messageId: row.messageId,
    uploadedBy: row.uploadedBy,
    filename: row.filename,
    mimeType: row.mimeType,
    sizeBytes: row.sizeBytes,
    storageProvider: row.storageProvider,
    storagePath: row.storagePath,
    processingStatus: row.processingStatus,
    safetyStatus: row.safetyStatus,
    createdAt: row.createdAt.toISOString(),
    extraction: row.extraction
      ? {
          contentType: row.extraction.contentType,
          summary: row.extraction.summary,
        }
      : null,
    streamSlug: row.streamSlug,
    streamName: row.streamName,
    streamType: row.streamType,
    uploaderSlug: row.uploaderSlug,
    uploaderName: row.uploaderName,
    referenceCount: row.referenceCount,
  }
}
